uc-cdis/cdis-jenkins-lib

Jenkinsfile
Change required after we reconfigured Jenkins to build "pull requests" instead of "branches that have been submit as pull requests" ... :-p
=> fix(Jenkinsfile): CHANGE_BRANCH - not BRANCH_NAME

vars/manifestHelper.groovy
Remove required certs from the jenkins-* envs config. The user agreement quiz is causing failed tests in `jenkins-blood` when the PR is on `cdis-manifest` because it is pulling the config from prod. In the future we can remove this, if we want to add integration tests for the quiz feature
=> fix(certs)

vars/securityPipeline.groovy
The pipeline to run automatic Veracode security scanning.
Runs every two weeks since Jun, 1 (every first Saturday of Sprint).
Can be manually triggered by the user.
Jenkins Veracode plugin must be installed: https://help.veracode.com/reader/PgbNZUD7j8aY7iG~hQZWxQ/DhfpJ3OQzjGCQ3M9mTzfhg
=> Security pipeline

vars/securityPipeline.groovy
github understands status `NOT_BUILT` as a failure, so we get red checks on all the commits in master
Possible statuses are SUCCESS, UNSTABLE, FAILURE, NOT_BUILT and ABORTED. I think SUCCESS is the only one that github shows as a success
=> fix(status)

vars/githubHelper.groovy, vars/kubeHelper.groovy, vars/microservicePipeline.groovy
This change will allow the user to pick which Jenkins environment should be used for the integration tests by applying a Github label on the PR.
This is very useful for troubleshooting and other experiments.
Some Jenkins environments might not be suitable for a given set of tests (for whatever reason) so this should help us achieve more control over our release flow until all the Jenkins environments are in an homogenous state.
@Alessandro / @marcelo https://ctds-planx.atlassian.net/browse/PXP-5155 I made a bug report for one of the issues we ran into yesterday: PRs against cdis-manifest for internalstaging are NOT running the google tests, PRs against Prod are though
I think :this: is pretty critical to get fixed sooner rather than later. We won't catch actual bugs with Google Data …
=> chore(qa): GitHub label magic

vars/microservicePipeline.groovy
We are now running the full suite of tests every time we update a markdown file, which is time-consuming and even locks a Jenkins environment that could be used in a real PR check.
That leads people to force merge PRs, which leaves a trail of inconsistent PRs.
To address that, we can use a `doc-only` label in the PRs that are related to documentation updates.
Successful test for reference:
https://jenkins.planx-pla.net/blue/organizations/jenkins/CDIS%20GitHub%20Org%2Fgen3-qa/detail/PR-229/6/pipeline/10
=> chore(QA): Avoid unnecessary tests while updating documentation

vars/docOnlyHelper.groovy, vars/microservicePipeline.groovy
To avoid some irresponsible usage of the `doc-only` PR label, this logic will make sure that the list of modified files in the PR is solely comprised of:
- Markdown files (ending with the `.md` extension)
- Files under a `releases` folder that sits in the root directory of the repo (this is needed so we can document the Gen3 Core Release artifacts -- A better approach can be considered later).
Successfully tested here:
https://github.com/uc-cdis/gen3-qa/pull/245
=> chore(qa): Improve  behavior for the "doc-only" PR label

vars/docOnlyHelper.groovy, vars/manifestHelper.groovy
While trying to introduce a githook script to the `cdis-manifest` repo,  the groovy pipeline tries to find a `manifest.json` inside the `.githooks` folder 🤦‍♂ . This is a quick measure to avoid that.
=> chore(qa): Skip tests for githooks

vars/docOnlyHelper.groovy
There is no need to run tests if the PR only contains markdown files and images.
=> chore(qa): Skip tests if the PR contains only md and images

vars/microservicePipeline.groovy, vars/testHelper.groovy
This new argument allows developers to pick a specific test script to be executed to retry one specific failed test (this is a mitigation measure to handle seasonal flaky tests).
The PR labels should follow the syntax below:
test-<suite_folder>-<name_of_the_script_without_extension>
e.g.,
test-google-googleDataAccessTest
=> chore(qa): Selecting specific feature to facilitate retry

vars/microservicePipeline.groovy, vars/testHelper.groovy
Looks like Jenkins doesn't like empty strings as default values.
Causing failures:
```
StackTrace:
hudson.AbortException: aborting build - testsuite failed
at org.jenkinsci.plugins.workflow.steps.ErrorStep$Execution.run(ErrorStep.java:63)
at org.jenkinsci.plugins.workflow.steps.ErrorStep$Execution.run(ErrorStep.java:50)
at org.jenkinsci.plugins.workflow.steps.SynchronousStepExecution.start(SynchronousStepExecution.java:38)
at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
at groovy.lang.MetaClassImpl.invokeMethodOnGroovyObject(MetaClassImpl.java:1278)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1172)
at …
```
=> chore(qa): Set default value for selectedTest argument

vars/microservicePipeline.groovy, vars/testHelper.groovy
Need to run specific health checks based on the value of the testedEnv variable, the groovy pipeline logic needs to pass this variable to the `check-pod-health.sh` bash script from `gen3-qa`.
=> chore(qa): Set testedEnv as arg to health check script

vars/kubeHelper.groovy
we want to pick a random index in `namespaces` (size 5), let's say 2, and then check all the namespaces in order: 2, 3, 4, 0, 1 (initial index + 0, initial index + 1, initial index + 2...)
that doesn't work if we overwrite the initial index
```
int randNum = new Random().nextInt(namespaces.size());
for (int i=0; i < namespaces.size(); ++i) {
randNum = (randNum + i) % namespaces.size();
...
```
- Try to lock each namespace
=> fix random namespace selection

vars/docOnlyHelper.groovy
This should augment the `doc-only` PR label logic to ignore changes in files that live inside dot folders.
Required to deliver this:
https://github.com/uc-cdis/cdis-manifest/pull/1535/files
Tested in `/script`:
=> chore(qa): Skip tests for changes in dot folders

vars/microservicePipeline.groovy
This is no longer necessary.
As per: https://github.com/uc-cdis/gitops-qa/pull/519
Reverts uc-cdis/cdis-jenkins-lib#84
=> Revert "chore(qa): Do not modify manifests when introducing a new CI environment"

vars/microservicePipeline.groovy, vars/testHelper.groovy
Tested in: https://github.com/uc-cdis/gen3-qa/pull/334
by overriding the Jenkins lib in the `Jenkinsfile`:
```
@Library('cdis-jenkins-lib@chore/delete_gcp_svc_acct_keys_before_running_tests') _
```
This should prevent intermittent failures related to google tests.
=> chore(qa): Delete gcp svc acct keys before running tests to avoid intermittent failures in google tests

vars/manifestHelper.groovy
Currently, the manifest indexing sower jobs that are defined across all the Jenkins CI environments (https://github.com/uc-cdis/gitops-qa/blob/master/jenkins-blood.planx-pla.net/manifest.json#L45) are being merged with the `manifest.json` from various environments from `cdis-manifest` that do not have such jobs enabled, which is erroneously triggering the @indexing / Indexing GUI test suite.
This change will empty the `sower` block from the Jenkins CI environments' `manifest.json` before environment-specific sower jobs can be added to the config.
=> chore(qa): Don't merge existing sower jobs defined for Jenkins CI envs

vars/manifestHelper.groovy
The sower blocks need to be mutated with the proper k8s service account that corresponds to the selected Jenkins namespace.
=> chore(qa): Set jenkins service account for sower jobs

vars/microservicePipeline.groovy
Due to the introduction of the new Jenkins worker (`gen3-qa-worker`), Jenkins is randomly assigning PR checks to the new worker. But the worker image doesn't have all the required dependencies to run PR checks (e.g., python3.6, jq and other CLI utilities).
We need to make sure that pipeline jobs will run only on the Jenkins `master` node.
=> chore(qa): PR Checks must run on the master jenkins container only

vars/manifestHelper.groovy
That previous logic was creating duplicate entries. This should set all the sower jobs from a manifest-based repo's PR `as-is`.
- No more duplicate sower job config entries.
=> fix(qa): Replace sower block instead of concatenating

vars/quayHelper.groovy
Minor fix to properly determine when a Quay build is done.
Looks like there are newline characters found in the build phase string.
=> fix(qa): Fix logic to check when the Quay build is completed

vars/gitHelper.groovy
Pull `gitops-qa-v2` source code when running PR checks for `v2` repos.
=> fix(qa): Pull v2 CI envs when running PRs on v2 repos

vars/microservicePipeline.groovy
Some of the PRs in `https://github.com/uc-cdis/indexs3client` are running the label check before the auto-label github action can automatically apply labels.
=> chore(qa): give auto-label a few seconds to catch up

vars/testHelper.groovy
Introducing `WithCredentials` block to load environment variables with service accounts to be used in CI tests.
The credentials have already been set up in Jenkins.
=> chore(qa): Introduce RAS Test credentials for CI tests

vars/xmlHelper.groovy
Some PRs are failing with:
```
+ ls output/*-testsuite.xml
ls: cannot access 'output/*-testsuite.xml': No such file or directory
script returned exit code 2
```
Even after the tests are executed successfully. We should ignore missing XMLs.
=> chore(qa): Ignore missing testsuite xmls

vars/manifestHelper.groovy
For some mysterious reason, potentially introduced by some recent Jenkins container level update, the manipulation of the sower block to mutate the list of sower-jobs and their correspondent service accounts was impacted and it led to misleading CI failures. More specifically, the sower block file that was supposed to contain the new service accounts is empty after the following operation:
```
cat sower_block.json | jq -r '.[] | if has("serviceAccountName") then .serviceAccountName = "jobs-jenkins-brain-planx-pla-net" else . end' | tee sower_block.json
— Shell Script
<1s
+ jq -r .[] | if has("serviceAccountName") then .serviceAccountName = "jobs-jenkins-brain-planx-pla-net" else . end
+ tee sower_block.json
+ cat sower_block.json
```
This code change has been tested here: …
=> fix(ci): Fix for sower block service account substitution

vars/microservicePipelineK8s.groovy, vars/testHelper.groovy
Required to support CI runs in qaplanetv2 / jenkins2 (against the experimental `ci-env-1` environment).
=> chore(ci2): Also delete svc acct keys for ci-env-1

vars/docOnlyHelper.groovy
Adding a new extension to the `doc-only` label criteria.
=> chore(qa): Add pdf to doc-only criteria

vars/xmlHelper.groovy
Prevent misleading failures in the PR Check if, for whatever reason, the CodeceptJS reports are not created under the `output` folder.
e.g.,
```
full list of failedTestSuites: []
+ ls output/result*.xml
ls: cannot access 'output/result*.xml': No such file or directory
script returned exit code 2ERROR: script returned exit code 2
StackTrace:
hudson.AbortException: script returned exit code 2
```
=> chore(qa): Avoid misleading 'No such file or directory' error msg

vars/microservicePipeline.groovy
This is blocking this: https://github.com/uc-cdis/gitops-qa/pull/1071
and this: https://github.com/uc-cdis/gen3-qa/pull/505
=> chore(midrc): Temporarily removing jenkins-brain from pool of ci envs until the new login/logout flow logic is tested

vars/microservicePipeline.groovy
In order to facilitate the selection of an environment that is "cordoned", we need to improve the logic to pick one of the Jenkins environments in case we need to remove one of them out of the CI pool and utilize it for ephemeral experiments.
=> chore(qa): Tweak the environment selection logic

vars/microservicePipeline.groovy
Reverts uc-cdis/cdis-jenkins-lib#134
=> Revert "chore(midrc): Temporarily removing jenkins-brain from pool of ci envs until the new login/logout flow logic is tested"

vars/quayHelper.groovy
Do not wait for image builds while testing a DD Repos PR
=> fix(ci): Do not wait for image builds while testing a DD Repos PR

vars/manifestHelper.groovy
There’s some automation that deletes any dash / hyphen from the data dictionary repo name right before publishing its branch-based URL.
e.g.,
REPO_NAME = gtex-dictionary
This works:
https://s3.amazonaws.com/dictionary-artifacts/gtexdictionary/chore/testing_this_dd_againstci/schema.json
This doesn’t work:
https://s3.amazonaws.com/dictionary-artifacts/gtex-dictionary/chore/testing_this_dd_againstci/schema.json
=> fix(qa): DD URLs can't have hyphens

vars/quayHelper.groovy
Let us investigate what happened here:
```
[Pipeline] { (WaitForQuayBuild)
[Pipeline] echo
Waiting for Quay to build:
repoName: fence
branch: 'chore_update-deps-test'
commit: 1c5792c3
previous commit: 3d554cdf
[Pipeline] echo
currentTime is: 1610408314
[Pipeline] sleep
Sleeping for 15 sec
[Pipeline] echo
running time query
[Pipeline] sh
+ curl -s https://quay.io/api/v1/repository/cdis/fence/build/?since=1610403026
+ jq .builds[] | "\(.tags[]),\(.display_name),\(.phase)"
[Pipeline] echo
time query failed, running limit query
[Pipeline] sh
+ curl -s https://quay.io/api/v1/repository/cdis/fence/build/?limit=25
+ jq .builds[] | "\(.tags[]),\(.display_name),\(.phase)"
[Pipeline] error
```
=> chore(ci): Debug WaitForQuayBuild

vars/quayHelper.groovy
In a recent Jenkins failure we got the following values:
```
currentTime is: 1610573413
GMT: Wednesday, January 13, 2021 9:30:13 PM
Your time zone: Wednesday, January 13, 2021 3:30:13 PM GMT-06:00
```
--
```
timeout is: 1610573358
GMT: Wednesday, January 13, 2021 9:29:18 PM
Your time zone: Wednesday, January 13, 2021 3:29:18 PM GMT-06:00
```
The timeout was at a point one minute before the currentTime.
Which led to the following failure:
```
if(currentTime > timeout) {
currentBuild.result = 'ABORTED'
error("aborting build due to timeout")
}
```
~Let us bump this up to 90 mins as a temporary measure until this code can be refactored and a better solution comes into play.~
**UPDATE:**
Let us use current time + 1hr instead of the starting time of the jenkins build.
=> chore(ci): Use current time +1hr instead of the starting time of the jenkins build

vars/xmlHelper.groovy
The Jenkins notification on Slack is suggesting labels for test suites that are passing tests after retries, this new code should avoid that.
=> chore(qa): If test suite succeeds on retries, do not suggest its label

vars/quayHelper.groovy
Having the current time defined as an Integer is messing with the `currentTime > timeout` check and it's dragging the while pipeline runtime.
=> fix(ci): Fix QuayHelper logic to give up on failed docker builds

vars/manifestHelper.groovy
e.g.
The following environment's manifest:
https://github.com/uc-cdis/gitops-qa/blob/master/qa-bloodpac.planx-pla.net/manifest.json
does *not* have the portal config block and the nct bundle is being erroneously injected because the `jenkins-niaid` manifest is NOT mutating according to the testedEnv. Therefore, that portal config should be removed for such test cases.
=> chore(ci): Remove portal config if selected env does not have it

vars/microservicePipeline.groovy
We need to enable ALL test suites for our nightly builds.
=> chore(night-build): Enable additional tests for our nightly builds

vars/microservicePipeline.groovy, vars/quayHelper.groovy
Addressing this issue that is blocking open source contribution testing:
```
ERROR: aborting build due to out of date git hash
pipeline commit: b7770bfe
quay: 53c4a17
StackTrace:
hudson.AbortException: aborting build due to out of date git hash
pipeline commit: b7770bfe
quay: 53c4a17
at org.jenkinsci.plugins.workflow.steps.ErrorStep$Execution.run(ErrorStep.java:63)
```
=> chore(open-source): Do not abort build for out of date git commits from open source contributions

vars/githubHelper.groovy
While delivering some refactoring code for the open source contributions’ automation…
I broke the test suite selection through labels 😄  So all PRs are running ALL tests (labels are being ignored).
That’s because we obtain PR metadata through an URL like this:
`https://api.github.com/repos/uc-cdis/cdis-manifest/pulls/2822`
BUT, for labels, the Github API designers thought it would be a good idea to change that URL context to issues instead of pulls 🤦🏼 
`e.g., https://api.github.com/repos/uc-cdis/cdis-manifest/issues/2822/labels`
=> fix(labels): Restore test suite selection through labels

vars/kubeHelper.groovy, vars/pipelineHelper.groovy
fix this issue:
```
+ bash /var/jenkins_home/workspace/GitHub_Org_cdis-manifest_PR-2848/cloud-automation/gen3/bin/save-failed-pod-logs.sh
INFO: 22:10:41 - capturing and archiving logs from failed pods (if any)...
+ mv save-failed-pod-logs.log gen3-qa/output/
mv: cannot move 'save-failed-pod-logs.log' to 'gen3-qa/output/': Not a directory
The Gen3 save logs operation failed.
```
=> fix(k8s-debugging): Drop logs on root folder of the PR workspace

vars/kubeHelper.groovy, vars/microservicePipeline.groovy
Send slack notifications for K8sReset failures with URL.
This should give us a feeling of how often we face such failures (in addition to metrics on https://qa.planx-pla.net/grafana/d/qiqUaOgMz/ci-metrics).
=> chore(ci-observability): Send slack notifications for K8sReset failures

vars/microservicePipeline.groovy
Let us avoid false alerts and noise on #gen3-qa-notifications
=> chore(ci-observability): hudson.AbortException should not be considered a k8sReset failure

vars/manifestHelper.groovy
If the target environment manifest doesn’t have netpolicy, we need to delete the `netpolicy: "on"`  from the jenkins-* manifest.json and then `$ gen3 kube-setup-indexd`  will NOT create the network policies
=> Fix: delete netpolicy in jenkins when target environment manifest does not have it

vars/ciEnsPoolHelper.groovy
This is a workaround to support the replay function on old cloud-automation PRs.
=> chore(ci): Create bridge function to support typo for old cloud-automation PRs

vars/microservicePipeline.groovy, vars/microservicePipelineK8s.groovy, vars/performancePipeline.groovy, vars/testHelper.groovy
Fix this issue: 
> jenkins failed twice in a row with error No test report files were found. Configuration error? after skipping the tests with label doc-only
=> Fix: Allow empty junit result when doNotRunTest is true

vars/manifestHelper.groovy
Fixing this error:
```
jenkins@jenkins-deployment-87585c94-dmr5t:~/workspace/GitHub_Org_cdis-manifest_PR-2933$ jq sower_block.json
jq: error: sower_block/0 is not defined at <top-level>, line 1:
sower_block.json
jq: 1 compile error
```
=> fix(ci): fix jq instruction to print sower_block.json

vars/manifestHelper.groovy
```[Pipeline] sh
+ jq -r . sower_block.json
null
[Pipeline] echo
0
[Pipeline] sh
+ cat sower_block.json
+ jq -r .[] | if has("serviceAccountName") then .serviceAccountName = "jobs-jenkins-dcp-planx-pla-net" else . end
jq: error (at <stdin>:1): Cannot iterate over null (null)```
the `sh` produces a null result and the return code is zero. So the fix will check if there is actual data in the `sower_block,json`
=> Change the logic for sower block in manifestHelper

vars/microservicePipeline.groovy
If we obtain the `testedEnv` value from the `environment` parameter found inside the corresponding `manifest.json`'s global config block, that will be a more accurate way of making our automated tests aware of which environment is being tested.
Explaining the issue:
The nightly build job picks one environment at random:
```
commons=("gen3.theanvil.io" "chicagoland.pandemicresponsecommons.org" "gen3.biodatacatalyst.nhlbi.nih.gov" "nci-crdc.datacommons.io" "data.braincommons.org" "vpodc.org")
selectedCommons=${commons[$RANDOM % ${#commons[@]} ]}
```
But the name of the folder is still nightly.planx-pla.net , and that folder name is passed on to the testing framework as a testedEnv variable.
That `testedEnv` variable is used to determine which Selenium locators (css id / class, xpath, etc.) …
=> fix(nightly-build): testedEnv should be determined by global config, not by git diff folder

vars/ciEnvsHelper.groovy, vars/microservicePipeline.groovy
To obtain some control over the throughput of PRs / Jenkins tests between repos, we are splitting the pool of environments between:
- jenkins-envs-services.txt
and
- jenkins-envs-releases.txt
```
% curl -s https://cdistest-public-test-bucket.s3.amazonaws.com/jenkins-envs-services.txt
jenkins-genomel
jenkins-blood
jenkins-dcp
jenkins-brain
jenkins-niaid
% curl -s https://cdistest-public-test-bucket.s3.amazonaws.com/jenkins-envs-releases.txt
jenkins-genomel
jenkins-blood
jenkins-dcp
jenkins-brain
jenkins-niaid
```
All cdis-manifest PRs will fetch the pool of CI environments from `jenkins-envs-releases.txt` whereas all the service repo PRs will fetch CI envs from `jenkins-envs-services.txt`.
If we want to keep a balance between the PRs across all repos balance, we just leave 5 jenkins …
=> chore(ci): Introduce diff pools of environments

vars/ciEnvsHelper.groovy, vars/microservicePipeline.groovy
If we suspect jenkins-master is overwhelmed, we can send PR check jobs to this jenkins-ci-worker pod.
=> chore(ci): Introduce special label to run PR check on separate jenkins-ci-worker pod

vars/ciEnvsHelper.groovy, vars/microservicePipeline.groovy
Creating a split pool of CI environments to avoid having jenkins-master being overwhelmed with too many queued up jobs, this will send jobs to the jenkins-ci-worker pod based on the workload around service PRs and Release PRs.
=> chore(ci-throughput): All manifest PRs should run on gen3-ci-worker

vars/manifestHelper.groovy
The sower block is empty and the jenkins CI environments' manifests are not being mutated properly.
Sower jobs are failing.
=> fix(ci): Mutate sower block config correctly

vars/manifestHelper.groovy, vars/microservicePipeline.groovy
We need to know which environment is being tested, but the nightly build `cdis-manifest` folder is always the same.
So there is a new instruction inside this job https://jenkins.planx-pla.net/job/nightly-job-run/ 
```
jq --argjson obj '{"mutatedEnvHostname": "'"${selectedCommons}"'"}' '.global += $obj' < nightly.planx-pla.net/manifest.json-tmp > temp && mv temp nightly.planx-pla.net/manifest.json-tmp
```
to introduce a new parameter to the manifest's `global` config block.
=> chore(nightly-build): Identify which environment is being tested as part of the nightly build.

vars/testHelper.groovy
This PR https://github.com/uc-cdis/gen3-qa/pull/674
depends on this change so it can utilize the new environment variables for the jenkins username and the api token.
=> chore(ci-observability): Add Jenkins user api token to gather jenkins metrics

vars/pipelineHelper.groovy
Jira Ticket: [PXP-9867](https://ctds-planx.atlassian.net/browse/PXP-9867)
`.avro.log` [file from PFB Export tests](https://github.com/uc-cdis/gen3-qa/blob/268c6dd57757cbb31d4e4d9944ea259e91ac2570/suites/portal/pfbExportTest.js#L405) is not being archived by pipeline.
- Archive `**/output/*.log` files
=> (PXP-9867): Archive `**/output/*.log` files

vars/microservicePipelineK8s.groovy
Only deploy ci jobs on on demand nodes
=> fix(ci-jobs-on-demand-only): Only schedule ci jobs on ondemand nodes

vars/microservicePipeline.groovy
to prevent errors like
```
1 Evicted: The node was low on resource: ephemeral-storage. Container shell was using 549232Ki, which exceeds its request of 0. Container jnlp was using 6556Ki, which exceeds its request of 0.
```
=> Set ephemeral storage resource value

vars/gitHelper.groovy, vars/microservicePipeline.groovy
Change `git log --author=Jenkins --invert-grep -10 --pretty="format: %h"` to `git log -10 --pretty="format: %h"` because:
- git was updated to a new version in https://github.com/uc-cdis/cloud-automation/pull/2398
- `git log`'s `--invert-grep` now only works with the `--grep` param, not with the `--author` param ([ref](https://stackoverflow.com/questions/6889830/equivalence-of-git-log-exclude-author/70644305#70644305))
- there is no need to exclude commits anymore because we don't push commits with a "Jenkins" user
- Fix `git log` command to work with newer versions of `git`
=> Fix `git log` command to work with newer versions of `git`

vars/microservicePipeline.groovy
Jira Ticket: [GQE-151](https://ctds-planx.atlassian.net/browse/GQE-151)
Jenkins is throwing `hudson.AbortException` when the k8sReset times out after the recent version update. And this is preventing slack notifications and pod log archival.
[GQE-151]: https://ctds-planx.atlassian.net/browse/GQE-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Save pod logs and send slack messages for k8sRest failures

vars/kubeHelper.groovy
Reverts uc-cdis/cdis-jenkins-lib#287
Services are failing to start in subsequent PRs once they are deleted
=> Revert "Delete all services after the run"

Dockerfile, vars/testHelper.groovy
Link to JIRA ticket if there is one: 
- Sends nightly failures to dev-oncall
=> Send nightly failures to dev-oncall
