- vars/microservicePipeline.groovy
cloud-automation refactor support
> fix(klock): switch kube-lock to klock

- Jenkinsfile
- vars/fetchCode.groovy
- vars/microservicePipeline.groovy
* switch to `jenkins-*` k8s namespaces instead of `qa-*`
* tweak `Jenkinsfile` to work for PRs
* handle case when quay build is not pending
* look for lockable k8s namespace
* use gitops-qa repo for gitops manifests
* handle non-master branch in manifest rewrite sed regex
> WIP - chore(jenkins-namespace): use jenkins-*, not qa-*

- vars/microservicePipeline.groovy
due to new jenkins config to build PR's
> fix(CHANGE_BRANCH): not GIT_BRANCH

- vars/microservicePipeline.groovy
and remove setup-spark code from gen3-qa etl test suite that is hanging tests
> fix(DbResetK8sDeploy): add kube-setup-spark

- vars/microservicePipeline.groovy
Adds a "CleanS3" step to the pipeline, during which the files that were created by the integration tests in `~/s3-cleanup` get processed. Each file contains a list of GUIDs of files that were uploaded to S3 and that should be deleted. The files are in a central location so that if a Jenkins session fails to clean up the files it created, another session will do it.
> PXP-2206 Feat/s3 clean

- vars/manifestHelper.groovy
- vars/microservicePipeline.groovy
- vars/testHelper.groovy
Only run the Google tests on cdis-manifest PRs if the changes are for a commons that uses DCF features (PXP-2758)
gen3-qa PR: https://github.com/uc-cdis/gen3-qa/pull/109
> feat(hostname-param): call run-tests.sh with param

- vars/securityPipeline.groovy
* Use `zip` with special `.secinclude` and `.secexclude` files, instead of `.gitattributes`.
Related PRs per project:
https://github.com/uc-cdis/fence/pull/719
https://github.com/uc-cdis/indexd/pull/247
https://github.com/uc-cdis/peregrine/pull/151
https://github.com/uc-cdis/sheepdog/pull/313
https://github.com/uc-cdis/gen3-arranger/pull/15
https://github.com/uc-cdis/data-portal/pull/601
> feat(sec): move from 'git archive' to just 'zip'

- Jenkinsfile
- vars/manifestHelper.groovy
- vars/microservicePipeline.groovy
- vars/performancePipeline.groovy
- vars/pipelineHelper.groovy
- vars/quayHelper.groovy
> fix(docker): add quayRegistry flag

- vars/microservicePipeline.groovy
- vars/testHelper.groovy
Identifying new gen3-release PR label to enable additional testing and triggering release automation
> Chore(QA): Identify gen3-release label

- vars/docOnlyHelper.groovy
doc_only tag support extended to .txt and .feature files
> Add doc_only support for txt and feature files

- vars/microservicePipeline.groovy
Pull the latest code to pick up changes from data-simulator, cloud-automation, gen3-qa, etc
> chore(qa): Clean workspace at the beginning of every PR check

- vars/kubeHelper.groovy
* setup klock lock to timeout after 2 hours instead of 1
> fix(klock): lock for 2 hours

- vars/docOnlyHelper.groovy
Skip tests for swagger yaml updates.
> chore(doc) skip tests for OpenAPI Swagger docs

- vars/docOnlyHelper.groovy
> chore(QA): Skip tests for swagger doc updates

- vars/decommissionEnvHelper.groovy
- vars/microservicePipeline.groovy
This should help people avoid force-merges.
> chore(qa): Skip tests to decommission envs

- vars/microservicePipeline.groovy
This effort is part of the Innovation Day.
> chore(qa): Run PR Check against qaplanetv2 if PR label is found

- vars/microservicePipeline.groovy
Innovation day: Introducing a new CI env to qaplanetv2.
> chore(qa): Do not modify manifests when introducing a new CI environment

- vars/manifestHelper.groovy
This is needed to investigate issues with the mutation of the manifest when a Jenkins CI environment is selected during the PR check flow.
> chore(qa): Additional debugging lines for the Jenkins service account replacement logic

- vars/docOnlyHelper.groovy
> chore(qa): Ignore spreadsheets when using the doc-only label

- vars/githubHelper.groovy
- vars/microservicePipeline.groovy
Aborting the CI run if a PR is marked as a draft.
Testing:
> chore(qa): Abort PR check if the PR is marked as a draft

- vars/microservicePipeline.groovy
- vars/microservicePipelineK8s.groovy
- vars/testHelper.groovy
Need to retry multiple test suites? This change is for you.
Testing:
> chore(qa): Support multiple test labels

- vars/testHelper.groovy
Enable Slack notifications for CI failures.
> chore(qa): Slack notification for ci failures

- vars/testHelper.groovy
- vars/xmlHelper.groovy
> chore(qa): Improve CI failure notifications suggesting labels

- vars/microservicePipelineK8s.groovy
e.g.,
https://jenkins2.planx-pla.net/blue/organizations/jenkins/planx-ci-pipeline%2Fgitops-qa-v2/detail/PR-8/2/pipeline
> fix(qa): MicroserviceK8s pipeline is presenting connectivity issues

- vars/microservicePipelineK8s.groovy
Small fix to unblock the tests in Jenkins2 / qaplanetv2
> fix(qa): Fix k8s pipeline by allowing multiple test labels

- vars/manifestHelper.groovy
Just removing TODOs and improving code comments.
> doc(qa): Improve code comments for manifestHelper.groovy

- vars/metricsHelper.groovy
- vars/microservicePipeline.groovy
We need more metrics to determine how often a given pipeline stage fails so we can prioritize improvements accordingly.
> chore(metrics): Write metrics for every pipeline stage

- vars/metricsHelper.groovy
- vars/microservicePipeline.groovy
Reverts uc-cdis/cdis-jenkins-lib#113
> Revert "chore(metrics): Write metrics for every pipeline stage"

- vars/manifestHelper.groovy
Another fix related to the null sower_block.json check.
> fix(ci): Sower block null check

- vars/microservicePipeline.groovy
- vars/quayHelper.groovy
> chore(qa): Skip WaitForQuayBuild stage for cdis-jenkins-lib PRs

- vars/manifestHelper.groovy
copy `portal` block in `manifest` over
- copy `portal` block in `manifest` over
> feat: copy portal block

- vars/manifestHelper.groovy
Reverts uc-cdis/cdis-jenkins-lib#123
> Revert "feat: copy portal block"

- vars/manifestHelper.groovy
This config block was never replaced.
That might explain the flakyness around the data file upload test 🤷
> fix(ci): Mutate indexs3client blocks in jenkins environments manifests

- vars/microservicePipeline.groovy
extend sleep time from 10s to 30s for auto-label actions to catch up
> longer time for auto-label actions to catch up

- vars/gitHelper.groovy
- vars/manifestHelper.groovy
- vars/microservicePipeline.groovy
We are introducing Jenkins tests to all DD repos to left-shift and capture regressions earlier in our CI pipelines.
Tested here: https://github.com/uc-cdis/gtex-dictionary/pull/101
> chore(CI): Introduce new Dictionary CI Flow

- vars/testHelper.groovy
> chore(psychological-safety): Notify successful CI runs

- vars/quayHelper.groovy
> fix(typo): fix quayHelper typo

- vars/testHelper.groovy
Make it easier for people to replay PRs through Slack.
> chore(ci): Improve instructions to replay flaky tests

- vars/testHelper.groovy
> fix(ci): Fix slack notification for PR failure msg

- vars/xmlHelper.groovy
Some PR failures are not presenting the labels correctly.
> fix(notifications): Fix labeling suggestion mechanism

- vars/xmlHelper.groovy
> Chore(ci): Fix labelling suggestion mechanism

- vars/xmlHelper.groovy
> fix(ci): Fix labeling suggestion mechanism again

- vars/testHelper.groovy
Issue: When a pr is labeled by multiple tests label, slack won't send failure notification if the last test is passed even though there are failed tests.
> fix(ci): fix misleading successful slack msg

- vars/kubeHelper.groovy
- vars/microservicePipeline.groovy
- vars/pipelineHelper.groovy
Save k8s pods logs when the `K8sReset` stage fails.
- Save k8s pods logs when the `K8sReset` stage fails.
> chore(k8s-debug): Save k8s pods logs if K8sReset fails

- vars/githubHelper.groovy
- vars/kubeHelper.groovy
- vars/microservicePipeline.groovy
> chore(open-source): Identify forked-repo branches

- vars/githubHelper.groovy
> chore(refactoring): Tweak fetch pr labels code

- vars/microservicePipeline.groovy
- vars/quayHelper.groovy
chore(open-source): Unblock CI for open source contributions
> chore(open-source): Unblock CI for open source contributions

- vars/microservicePipeline.groovy
- vars/testHelper.groovy
Send nightly-build results to special channel
> chore(nightly-build): Send Slack notification to special channel

- vars/quayHelper.groovy
fix(open-source): Identify automatedCopy img builds that match the branch name
> fix(open-source): Identify automatedCopy img builds that match the branch name

- vars/microservicePipelineK8s.groovy
Update k8s microservices pipeline script
> chore(k8s-jenkins-ci): Update k8s microservices pipeline script

- vars/testHelper.groovy
- vars/xmlHelper.groovy
Experimenting new label mechanism by only parsing result*.xml
> Chore(ci): Modify label mechanism by only parsing result*.xml

- vars/docOnlyHelper.groovy
- Handle swagger doc at any path
> Handle swagger doc at any path

- vars/microservicePipeline.groovy
> fix(ci): doc-only flow should not rely on testedEnv

- vars/testHelper.groovy
Improving labelling suggestion for nightly builds.
> chore(nightly-build): Include nightly-run label when sending replay msgs

- vars/microservicePipeline.groovy
Additional logging for `testedEnv` var.
> fix(logging): print testedEnv

- vars/manifestHelper.groovy
removing the double quotes around length function in sower block
> fix : double quotes to check the length func sower block

- vars/microservicePipeline.groovy
Proper fix to set `testedEnv` to a correct value.
> fix(ci): Setting testedEnv properly for service, manifest and nightly-builds CI runs

- vars/microservicePipeline.groovy
- vars/microservicePipelineK8s.groovy
Jira Ticket: [PXP-8168](https://ctds-planx.atlassian.net/browse/PXP-8168)
Tested here: https://github.com/uc-cdis/gen3-qa/pull/635
- Automatically skip tests if changes are doc-only, instead of relying on a label
> PXP-8168 Automatically skip tests if changes are doc-only

- .pre-commit-config.yaml
- vars/microservicePipeline.groovy
Sleep before fetching the PR labels, not after
> Sleep before fetching the PR labels

- vars/microservicePipeline.groovy
Creating a split pool of CI environments to avoid having jenkins-master being overwhelmed with too many queued up jobs, this will send jobs to the `jenkins-ci-worker` pod based on the workload around service PRs and Release PRs.
> chore(ci-throughput): Capture pipeline config to make sure all manifest PRs run on gen3-ci-worker

- vars/microservicePipeline.groovy
Indicate which Jenkins environments the build is running against in the build name
> Add namespace in build name

- vars/microservicePipeline.groovy
fix issue when locking the namespace for several attempts, the namespace can't show properly
> display namespace after try block

- vars/testHelper.groovy
Delete 3rdParty resources from new jenkins env.
Based on
```
$ grep "jnew" Gen3Secrets/apis_configs/*
Gen3Secrets/apis_configs/fence-config.yaml:GOOGLE_GROUP_PREFIX: jnew
Gen3Secrets/apis_configs/fence-config.yaml:GOOGLE_SERVICE_ACCOUNT_PREFIX: jnew
```
> chore(ci-mgmt): Delete 3rdParty resources from new jenkins env

- vars/microservicePipeline.groovy
First addition of long-running test to our nightly-build routine.
> chore(nightly-build): Improve nightly-build test coverage with long-running tests

- vars/microservicePipeline.groovy
> fix(nightly-build): Fix nightly build test addition

- vars/testHelper.groovy
Print jenkins namespace with CI Failure msg
> chore(ci): Print jenkins namespace with CI Failure msg.

- vars/manifestHelper.groovy
Related to https://github.com/uc-cdis/cdis-manifest/pull/3332
Jira Ticket: [HP-291](https://ctds-planx.atlassian.net/browse/HP-291)
* Handle `metadata` as a manifest key
* Break out common config handling into a loop
> feat(metadata): add manifest config changes

- vars/microservicePipelineK8s.groovy
> fix(nightly-build): Notification should include the name of the selected environment

- vars/manifestHelper.groovy
Aggregate metadata config was not getting copied when running PRs. This is to address the issue
> copy metadata folder

- vars/gitHelper.groovy
- vars/manifestHelper.groovy
> agg mds config

- vars/testHelper.groovy
Introduce more details to the successful nightly build notification.
> chore(nithgly-build): Add nightly build details to successful msg

- vars/manifestHelper.groovy
Jira Ticket: [PXP-8908](https://ctds-planx.atlassian.net/browse/PXP-8909)
add mariner to manifest merge
> feat add mariner to manifest merge

- vars/manifestHelper.groovy
> do not use defaults for manifest nodes not present in the PR

- vars/microservicePipelineK8s.groovy
> skip quay build label

- vars/microservicePipelineK8s.groovy
> capture repo name before skipping quay build

- vars/microservicePipelineK8s.groovy
> increase runTests timeout to 2 hours

- vars/microservicePipelineK8s.groovy
increase timeout for `ModifyManifest` step in the pipeline for covid19 PRs
> increase the timeout for K8Reset step

- vars/microservicePipelineK8s.groovy
> Increase runTests timeout to 3 hours

- vars/microservicePipelineK8s.groovy
Jira Ticket: [PXP-9890](https://ctds-planx.atlassian.net/browse/PXP-9890)
- Only run nightly build PFB export tests when enabled for selected environment
> (PXP-9890): Only run nightly build PFB export tests when enabled for selected env

- vars/microservicePipeline.groovy
- vars/microservicePipelineK8s.groovy
- vars/testHelper.groovy
> run tests in debug mode if labeled or running specific tests

- vars/gitHelper.groovy
- vars/microservicePipelineK8s.groovy
- vars/quayHelper.groovy
Jira Ticket: [QAT-411](https://ctds-planx.atlassian.net/browse/QAT-411)
> Fix quayHelper to support GH workflows for building images

- vars/docOnlyHelper.groovy
- Fix doc-only logic: iterate over all files changed in the env
> Fix doc-only logic: iterate over all files changed in the env

- vars/kubeHelper.groovy
- vars/microservicePipeline.groovy
- vars/microservicePipelineK8s.groovy
> Log namespaces pool

- vars/microservicePipelineK8s.groovy
> Increase K8Reset timeout for covid19 portal pods

- vars/docOnlyHelper.groovy
To avoid skipping tests when there are changes to requirements.txt
> Remove docOnly handler for .txt files

- vars/kubeHelper.groovy
- vars/microservicePipeline.groovy
[GQE-30](https://ctds-planx.atlassian.net/browse/GQE-30)
[GQE-30]: https://ctds-planx.atlassian.net/browse/GQE-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Delete deployments after test run

- vars/microservicePipeline.groovy
Update the required scheduling constraints to work with karpenter
> fix(ci-jobs): Update the required scheduling constraints to work with karpenter

- vars/microservicePipeline.groovy
> Remove the setting added for debugging self signed certificate issue

- vars/microservicePipeline.groovy
> Do not clean S3 and k8s if tests don't run

- vars/microservicePipeline.groovy
> testing ephemeral-storage in PR pod

- vars/microservicePipeline.groovy
> Use initcontainer to wait for jenkins connection

- vars/gitHelper.groovy
- vars/microservicePipeline.groovy
[GQE-71](https://ctds-planx.atlassian.net/browse/GQE-71)
[GQE-71]: https://ctds-planx.atlassian.net/browse/GQE-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Separate selenium container in pr pod

- vars/microservicePipeline.groovy
[GQE-97](https://ctds-planx.atlassian.net/browse/GQE-97)
[GQE-97]: https://ctds-planx.atlassian.net/browse/GQE-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Support for label to skip jenkins env cleanup

- vars/microservicePipeline.groovy
Jira Ticket: [GQE-100](https://ctds-planx.atlassian.net/browse/GQE-100)
[GQE-100]: https://ctds-planx.atlassian.net/browse/GQE-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use ECR for selenium image

- vars/gitHelper.groovy
> Use older tag of data-simulator

- vars/testHelper.groovy
> Add GCP cleanup for missing environments

- vars/manifestHelper.groovy
> Remove netpolicy from global block of manifest

- vars/kubeHelper.groovy
> Delete all services after the run

- vars/microservicePipeline.groovy
Jira Ticket: [GQE-183](https://ctds-planx.atlassian.net/browse/GQE-183)
[GQE-183]: https://ctds-planx.atlassian.net/browse/GQE-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Increase resources for jenkins worker container
